version: '3.8'
services:
    mysql:
        image: mysql:latest
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ~/mysql-docker-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1qaz2wsx
            MYSQL_DATABASE: golearn
        ports:
            - "3306:3306"
